i=1
totalJ1=0
totalJ2=0
totalJ3=0
lancer1=0
lancer2=0
lancer3=0
zone1=0
zone2=0
zone3=0
print("LES REGLES DU JEU :")
print("5 manches de 3 lancer")
print("zone 1 : 1 point")
print("zone 2 : 2 points")
print("zone 3 : 3 points")
print("3 lancer réussi : 3 points bonus")
print("celui qui a le plus de points gagne")
print("ALORS A VOS BOULETTES !!!")
nbdejoueur=int(input("Nombre de joueur = "))
if nbdejoueur==1:
    joueur1=input("joueur 1 = ")
    while i<=5:
        print("manche ",end='')
        print(i)
        print(joueur1,end='')
        print(" premier lancer")
        zone1=int(input("zone (1, 2 ou 3) ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone (1, 2 ou 3) ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone (1, 2 ou 3) ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ1=totalJ1+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ1=totalJ1+3
        print("Score")
        print(joueur1,end='')
        print(" = ",end='')
        print(totalJ1)
        i=i+1
    print("RESULTAT")
    print("1er = ",end='')
    print(joueur1,end=' ')
    print(" = ",end='')
    print(totalJ1)
elif nbdejoueur==2:
    joueur1=input("joueur 1 = ")
    joueur2=input("joueur 2 = ")
    while i<=5:
        print("manche ",end='')
        print(i)
        print(joueur1,end='')
        print(" premier lancer")
        zone1=int(input("zone (1, 2 ou 3) ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone (1, 2 ou 3) ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone (1, 2 ou 3) ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ1=totalJ1+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ1=totalJ1+3
        print("Score")
        print(joueur1,end='')
        print(" = ",end='')
        print(totalJ1)
        print(joueur2,end='')
        print(" premier lancer")
        zone1=int(input("zone ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ2=totalJ2+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ2=totalJ2+3
        print("Score")
        print(joueur2,end='')
        print(" = ",end='')
        print(totalJ12)
        i=i+1
    if totalJ1>totalJ2:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
        print("2eme = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
    elif totalJ1<totalJ2:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
        print("2eme = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
elif nbdejoueur==3:
    joueur1=input("joueur 1 = ")
    joueur2=input("joueur 2 = ")
    joueur3=input("joueur 3 = ")
    while i<=5:
        print("manche ",end='')
        print(i)
        print(joueur1,end='')
        print(" premier lancer")
        zone1=int(input("zone (1, 2 ou 3) ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone (1, 2 ou 3) ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone (1, 2 ou 3) ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ1=totalJ1+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ1=totalJ1+3
        print("Score")
        print(joueur1,end='')
        print(" = ",end='')
        print(totalJ1)
        print(joueur2,end='')
        print(" premier lancer")
        zone1=int(input("zone (1, 2 ou 3) ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone (1, 2 ou 3) ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone (1, 2 ou 3) ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ2=totalJ2+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ2=totalJ2+3
        print("Score")
        print(joueur2,end='')
        print(" = ",end='')
        print(totalJ2)
        print(joueur3,end='')
        print(" premier lancer")
        zone1=int(input("zone (1, 2 ou 3) ? = "))
        lancer1=int(input("1 pour reussi, 0 pour echec = "))
        print("deuxieme lancer")
        zone2=int(input("zone (1, 2 ou 3) ? = "))
        lancer2=int(input("1 pour reussi, 0 pour echec = "))
        print("troisieme lancer")
        zone3=int(input("zone (1, 2 ou 3) ? = "))
        lancer3=int(input("1 pour reussi, 0 pour echec = "))
        totalJ3=totalJ3+(lancer1*zone1)+(lancer2*zone2)+(lancer3*zone3)
        if lancer1==1 and lancer2==1 and lancer3==1:
            totalJ3=totalJ3+3
        print("Score")
        print(joueur3,end='')
        print(" = ",end='')
        print(totalJ3)
        i=i+1
    if totalJ1>totalJ2 and totalJ2>totalJ3:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
        print("2eme = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
        print("3eme = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
    elif totalJ1>totalJ3 and totalJ3>totalJ2:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
        print("2eme = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
        print("3eme = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
    elif totalJ2>totalJ1 and totalJ1>totalJ3:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
        print("2eme = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
        print("3eme = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
    elif totalJ2>totalJ3 and totalJ3>totalJ1:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
        print("2eme = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
        print("3eme = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
    elif totalJ3>totalJ1 and totalJ1>totalJ2:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
        print("2eme = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)
        print("3eme = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
    elif totalJ3>totalJ2 and totalJ2>totalJ1:
        print("RESULTAT")
        print("1er = ",end='')
        print(joueur3,end=' ')
        print(" = ",end='')
        print(totalJ3)
        print("2eme = ",end='')
        print(joueur2,end=' ')
        print(" = ",end='')
        print(totalJ2)
        print("3eme = ",end='')
        print(joueur1,end=' ')
        print(" = ",end='')
        print(totalJ1)




    
    


